import {leagueProfile} from './league.js';
// Illustrative player pool. Rankings and team labels are not a live feed.
const groups = {
WR: ['Ja’Marr Chase|CIN','Justin Jefferson|MIN','CeeDee Lamb|DAL','Puka Nacua|LAR','Amon-Ra St. Brown|DET','Nico Collins|HOU','Malik Nabers|NYG','Brian Thomas Jr.|JAX','A.J. Brown|PHI','Drake London|ATL','Ladd McConkey|LAC','Tee Higgins|CIN','Jaxon Smith-Njigba|SEA','Garrett Wilson|NYJ','Terry McLaurin|WAS','Mike Evans|TB','DJ Moore|CHI','DeVonta Smith|PHI','Zay Flowers|BAL','DK Metcalf|PIT','Xavier Worthy|KC','Courtland Sutton|DEN','George Pickens|DAL','Chris Olave|NO','Jaylen Waddle|MIA','Jameson Williams|DET','Jordan Addison|MIN','Rome Odunze|CHI','Ricky Pearsall|SF','Keon Coleman|BUF','Josh Downs|IND','Jakobi Meyers|LV','Michael Pittman Jr.|IND','Darnell Mooney|ATL','Cooper Kupp|SEA','Rashid Shaheed|NO','Christian Kirk|HOU','Marvin Harrison Jr.|ARI','Calvin Ridley|TEN','Jerry Jeudy|CLE'],
RB: ['Bijan Robinson|ATL','Jahmyr Gibbs|DET','Saquon Barkley|PHI','Ashton Jeanty|LV','Christian McCaffrey|SF','Derrick Henry|BAL','De’Von Achane|MIA','Josh Jacobs|GB','Jonathan Taylor|IND','Bucky Irving|TB','Kyren Williams|LAR','James Cook|BUF','Chase Brown|CIN','Breece Hall|NYJ','Kenneth Walker III|SEA','Omarion Hampton|LAC','Alvin Kamara|NO','James Conner|ARI','David Montgomery|DET','TreVeyon Henderson|NE','Chuba Hubbard|CAR','Aaron Jones|MIN','D’Andre Swift|CHI','Tony Pollard|TEN','Isiah Pacheco|KC','Jaylen Warren|PIT','Rhamondre Stevenson|NE','Brian Robinson Jr.|WAS','Travis Etienne Jr.|JAX','Zach Charbonnet|SEA','Tank Bigsby|JAX','Tyjae Spears|TEN','Trey Benson|ARI','Tyler Allgeier|ATL','Ray Davis|BUF','Blake Corum|LAR'],
QB: ['Josh Allen|BUF','Lamar Jackson|BAL','Jayden Daniels|WAS','Jalen Hurts|PHI','Joe Burrow|CIN','Patrick Mahomes|KC','Baker Mayfield|TB','Bo Nix|DEN','Kyler Murray|ARI','Dak Prescott|DAL','Justin Herbert|LAC','Caleb Williams|CHI','Brock Purdy|SF','Drake Maye|NE','Jared Goff|DET','Trevor Lawrence|JAX','Tua Tagovailoa|MIA','Jordan Love|GB','C.J. Stroud|HOU','Michael Penix Jr.|ATL','Bryce Young|CAR','Geno Smith|LV','Matthew Stafford|LAR','Sam Darnold|SEA'],
TE: ['Brock Bowers|LV','Trey McBride|ARI','George Kittle|SF','Sam LaPorta|DET','Travis Kelce|KC','T.J. Hockenson|MIN','Mark Andrews|BAL','David Njoku|CLE','Evan Engram|DEN','Tucker Kraft|GB','Dalton Kincaid|BUF','Jake Ferguson|DAL','Dallas Goedert|PHI','Kyle Pitts|ATL','Cole Kmet|CHI','Hunter Henry|NE'],
K: ['Brandon Aubrey|DAL','Cameron Dicker|LAC','Chris Boswell|PIT','Jake Bates|DET','Harrison Butker|KC','Ka’imi Fairbairn|HOU','Chase McLaughlin|TB','Tyler Bass|BUF','Jake Elliott|PHI','Jason Sanders|MIA','Wil Lutz|DEN','Younghoe Koo|ATL','Jason Myers|SEA','Evan McPherson|CIN','Cairo Santos|CHI','Matt Gay|WAS'],
DST: ['Denver Defense|DEN','Philadelphia Defense|PHI','Baltimore Defense|BAL','Pittsburgh Defense|PIT','Houston Defense|HOU','Minnesota Defense|MIN','Buffalo Defense|BUF','Green Bay Defense|GB','Kansas City Defense|KC','Los Angeles Defense|LAR','Detroit Defense|DET','Seattle Defense|SEA','San Francisco Defense|SF','Dallas Defense|DAL','Cincinnati Defense|CIN','Chicago Defense|CHI']
};
const offsets = {WR: 1, RB: 2, QB: 27, TE: 23, K: 145, DST: 140};
const scales = {WR: 2.8, RB: 3.1, QB: 6.5, TE: 9, K: 3, DST: 3};
export const samplePlayers = Object.entries(groups).flatMap(([position, names]) => names.map((entry, i) => {const [name, team] = entry.split('|'); return {id: `${position}-${i}`, name, team, position, rank: offsets[position] + i * scales[position]};})).sort((a,b)=>a.rank-b.rank).map((p,i)=>({...p,rank:i+1}));
export const defaultSettings = {...leagueProfile, slot: 5, slotConfirmed: true, leagueProfileVersion: 2};
export const slots = ['QB','RB','RB','WR','WR','TE','FLEX','K','DST','BN','BN','BN','BN','BN','BN','BN'];
